version: '3.1'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=policlinic
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
  backend:
    image: python:3.9.7
    depends_on:
      - db
      - redis
    build: ./backend
    volumes:
      - ./backend:/project/backend
    command: >
      bash -c "poetry install &&
      poetry run python manage.py makemigrations &&
      poetry run python manage.py migrate --fake-initial &&
      poetry run python -m gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
  frontend:
    image: node
    volumes:
      - ./nextjs-frontend:/project/frontend
    command: >
        bash -c "cd /project/frontend
        && yarn dev
        "
    depends_on:
      - backend
    ports:
      - 3000:3000



  