version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: polyclinic
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - 3308:3306