# Generated by Django 3.2.8 on 2021-11-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='polis',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
    ]
