# Generated by Django 3.2.8 on 2021-11-26 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polyclinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentDate', models.DateField(verbose_name='День приема')),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='Название дня недели')),
                ('index', models.IntegerField(blank=True, verbose_name='Номер дня недели')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentTime', models.TimeField(verbose_name='Время приема')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(max_length=50, null=True)),
                ('birthDate', models.DateField()),
                ('speciality', models.CharField(choices=[('Участковый врач', 'Участковый врач'), ('Уролог', 'Уролог'), ('Хирург', 'Хирург'), ('Оторноларинголог', 'Оторноларинголог'), ('Диспансеризация/Профилактический мед.осмотр', 'Диспансеризация/Профилактический мед.осмотр'), ('Офтальмолог', 'Офтальмолог'), ('Медицинский пост', 'Медицинский пост'), ('Вакцинация от COVID-19', 'Вакцинация от COVID-19'), ('Мазок на COVID-19 (ПЦР)', 'Мазок на COVID-19 (ПЦР)'), ('Кровь (антитела COVID-19)', 'Кровь (антитела COVID-19)')], max_length=200)),
                ('room', models.IntegerField(blank=True)),
                ('availableTimes', models.ManyToManyField(to='doctor.Time')),
                ('polyclinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyclinic.polyclinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workDays', models.ManyToManyField(to='doctor.DayOfWeek')),
            ],
        ),
    ]
