# Generated by Django 3.2.8 on 2021-11-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='patientComment',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
