# Generated by Django 3.2.8 on 2021-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_patientcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='patientComment',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
